### ISSUE TITLE
translateX/Y from mediaStyle not works

### ISSUE THREAD

**Issue by masalinas** [ValentinH/react-easy-crop#304]
**Describe the bug**
When apply translateX or translateY style from mediaStyle the image not move to any place

**To Reproduce**
Change translateX or translateY value from the sandbox

**Expected behavior**
The image must move from the translateX/Y set from mediaStyle

- Please create a CodeSandbox that demonstrates your issue. You can fork the Basic example: 
https://codesandbox.io/s/old-bash-vgoeu?file=/src/index.js

**Comment by ValentinH** [comment]
I don't understand what you mean. Could you please provide a sandbox showing the issue?

**Comment by masalinas** [comment]
I want to set a  fix hight and width crop area but to have the posibility of resize and relocate the image (dog file) at runtime. How can we do that? I used the mediaStyle style but I couldn't. 

This is the sandbox, it's your demo sandbox only adding this styles:
https://codesandbox.io/s/old-bash-vgoeu?file=/src/index.js

**Comment by ValentinH** [comment]
You are not able to set the `transform` on this element because the library is setting it as well in order to move the image.

**Comment by masalinas** [comment]
How can I translate (move X/Y) the image in runtime so with your component then?

**Comment by ValentinH** [comment]
I don't even understand what you are trying to do. You should be the one providing an example showing your real use case and then I could try to help. 🙂
