### ISSUE TITLE
Bug only in Safari

### ISSUE THREAD

**Issue by Andresargote** [ValentinH/react-easy-crop#345]
**Describe the bug**
There seems to be a bug in Safari, when I want to upload an image and shrink it the image is placed on the left side (when it should be in the center) in other browsers like Google or Brave it works correctly.

I will leave below a link to two videos:

1. [Correct functioning](https://jmp.sh/dpTY4m3)
2. [Unexpected operation in Safari](https://jmp.sh/7Dmoe4u)

Any help or clues as to what might be causing this error would be appreciated!.

**Comment by ValentinH** [comment]
When you log the output coordinates, do they look the same between Safari and Chrome?
If yes, then it's probably an issue with the cropImage.js file logic.

**Comment by Andresargote** [comment]
Hi @ValentinH this is my cropImage.js file in Chrome works correctly but the problem is with safari I can't find well what can it be.

Any help or idea is welcome!

`/**
 * This function was adapted from the one in the ReadMe of https://github.com/DominicTobias/react-image-crop
 * @param {File} image - Image File url
 * @param {Object} pixelCrop - pixelCrop Object provided by react-easy-crop
 * @param {number} rotation - optional rotation parameter
 */
export default async function getCroppedImg(imageSrc, pixelCrop, rotation = 0) {
  const image = await createImage(imageSrc)
  const canvas = document.createElement('canvas')

  const scaleX = image.naturalWidth / image.width;
  const scaleY = image.naturalHeight / image.height;

  canvas.width = pixelCrop.width;
  canvas.height = pixelCrop.height;

  const ctx = canvas.getContext('2d')
  ctx.fillStyle = "white";
  ctx.fillRect(0, 0, canvas.width, canvas.height);

  ctx.drawImage(
    image,
    pixelCrop.x * scaleX,
    pixelCrop.y * scaleY,
    pixelCrop.width * scaleX,
    pixelCrop.height * scaleY,
    0,
    0,
    pixelCrop.width,
    pixelCrop.height
  );

  return new Promise(resolve => {
    canvas.toBlob(file => {
      resolve(file)
    }, 'image/jpeg')
  })
}
js`

**Comment by ValentinH** [comment]
Sharing a codesandbox that I could use to reproduce the issue would greatly help me to help you 🙂
