### ISSUE TITLE
Cannot move image when changing uploaded image

### ISSUE THREAD

**Issue by Hellstellar** [ValentinH/react-easy-crop#355]
**Describe the bug**
The location of the image on cropper is not in center. And the whole image is also not visible, Also this image does not move.

**To Reproduce**
1. Choose image
2. Change image
3. If still works fine repeat above steps
I am not able to consistently reproduce this behaviour, But it is happening frequently with no exact pattern.
**Expected behavior**
The image should be consistently in the center of container, and moving gesture should not stop working

**To fix this**
Resize the window just a little(even if you open console) this fixes the issue

I am not able to reproduce this in a sandbox but here is the unlisted video on youtube for the issue: https://youtu.be/1Kwynjgil04

**Comment by Hellstellar** [comment]
I was able to reproduce the issue consistently by changing the height after media load but not sure if the issue is related to container height.

**Comment by Hellstellar** [comment]
This issue is most probably not related to the library, When moved it out of the container(which is a modal) It is working properly.. Still if someone is able to figure out the issue by watching the video please do comment the solution.

**Comment by ValentinH** [comment]
Did you set the container to be position relative?
