### ISSUE TITLE
Prevent from catching scroll events by cropper

### ISSUE THREAD

**Issue by MatixYo** [ValentinH/react-easy-crop#356]
**Is your feature request related to a problem? Please describe.**
When Cropper is added to a website with a scrollbar it then catches both mouse wheel scroll and swipe events making it hard to scroll past that Cropper.

**Describe the solution you'd like**
There was a similar problem on embedded Google maps and they prevented this from happening by requiring CTRL button to be pressed while mouse wheel event & requiring multi-touch interaction with the map.
There should be an additional prop added that allows you to turn that feature on & off. I'm not sure yet if there should be separate props for wheel & multiouch.

- If you have ideas on how to implement your new feature, please share!

Preventing wheel event should be fairly easy. `WheelEvent` has `ctrlKey` property that returns true if CTRL key was pressed. I'm not sure how that would work with timeouts that are inside of onWheel method.
When it comes to multitouch gestures this function should check if `e.touches.length >== 2`

- If you know any examples online that already implement such functionality, please share a link.

https://developers.google.com/maps/documentation/embed/embedding-map

**Comment by ValentinH** [comment]
I like this idea very much! Would you like to work on a PR for this?

**Comment by MatixYo** [comment]
Yeah, give me just a couple days

**Comment by MatixYo** [comment]
Check my proposed solution. I checked on desktop & mobile and it works quite nice.

**Comment by ValentinH** [comment]
This is now available in v4.1.0. See this demo: https://codesandbox.io/s/react-easy-crop-scroll-demo-fp21qd
