### ISSUE TITLE
Dynamic Images are Unable to crop at second attempt by using redux toolkit  

### ISSUE THREAD

**Issue by mmehmoodahmed** [ValentinH/react-easy-crop#362]
**Describe the bug**

I am trying to crop an image after the selection from a user end. 

First crop is working as expected but second crop/resize attempt displays the same image again and again.
The size of the image is not being reduced after the first attempt. 
I have tried to add my code at below url to see/analyze the complete code.

https://codesandbox.io/s/little-surf-v3euxf?file=/src/EditImageSlider.js

**To Reproduce**

I tried to upload a video link so that my reproduce steps could be seen with more detail.

Please see the below url

https://youtu.be/MSoehfNkLpQ

**Expected behavior**

Image Crop must be resized/cropped at every attempt and the size of the real image should be reduced.

[- Please create a CodeSandbox that demonstrates your issue. 

](https://codesandbox.io/s/little-surf-v3euxf?file=/src/EditImageSlider.js)

**Comment by ValentinH** [comment]
Your example is way too complex for me to help. I'm pretty sure this is a bug related to the integration and not within the library. Please try to create a minimal example showing the issue if you manage to do so.

**Comment by mmehmoodahmed** [comment]
Hi Valentin H. Thank you for replying.
Yes it seems so. 
I am using redux toolkit.
OK
I try to make it more simple then inform you.

**Comment by mmehmoodahmed** [comment]
Valentin H, 

Please now. I have much simplified the source. I have removed the unnecessary components now.

![image](https://user-images.githubusercontent.com/48244871/156924588-d5a798f1-ef52-4d0b-93e0-f5a1f3d8aed5.png)

You need to see this component 

`EditImageSlider.js `    

There are onSaveImage,  showImageForCrop,  onCropComplete, onCropperZoomChange and singlefileSelectedHandler functions

`singlefileSelectedHandler ` function is used when user select some image from the browser.

`onCropperZoomChange ` function is used when user perform zoom in and out operations.

`onCropComplete` function is used when cropper need to get the coordinated.

`onSaveImage ` function is used when user crop/resize some image and click on popup Apply button. and add the cropped image in the below list.

`imagecrop-actions.js` sendImageData function is being called to save the cropped image on server.


`showImageForCrop` function is used when user click on some image from the below saved image list to maintain the state through redux toolkit.   

`imagecrop-slice.js  ` keep the track of states for `EditImageSlider.js` component

I am available , if you want to understand the structure of my example. 

Please ask

**Comment by ValentinH** [comment]
Thanks for taking the time to simplify the example. However, I'm sorry but this is still too much for this kind of issue.
It doesn't seem to be a bug with the library but more an integration problem.

An advice I can share regarding the output is that you should avoid using the `cropSize` property as it makes the crop area super small. You should rather use the `aspect={1}` in your case and then you won't have to invert the zoom slider (can be from 1 to 4).

Another advice is to keep the original image until you sent it to the server. Like this, when clicking on the thumbnail, you are exactly in the same state than when you first cropped the image.

**Comment by mmehmoodahmed** [comment]
Hi, ValentinH,
Thank you for replying and sharing your valuable tips.

ValentineH, I have traced the issue and now fixing it.  

Actually the issue was at my server side. I am using sharp lib to resize or compress the images and sharp was using the cache

I disabled the cache and it started to work.
