### ISSUE TITLE
Can't import Point, Area types into a TypeScript project

### ISSUE THREAD

**Issue by metadiego** [ValentinH/react-easy-crop#369]
**Describe the bug**
When I follow the typescript tutorial for this module and I add: import { Point, Area } from 'react-easy-crop/types', I get the following error:

`Unable to resolve path to module 'react-easy-crop/types'
`

**To Reproduce**
1. Create typescript project which uses react-easy-crop
2. Set up basic typescript react-easy-crop example
3. Change baseUrl in tsconfig.json to "src"

**Expected behavior**
Should react-easy-crop export types?

**Comment by ValentinH** [comment]
What setup are you using to create the project?
We have a TS demo on Codesandbox where this import works fine: https://codesandbox.io/s/react-easy-crop-in-ts-lj1if?file=/src/App.tsx

**Comment by ValentinH** [comment]
However, it could be that we are missing an `exports` definition in our package.json for the `types` module.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉

**Comment by Rc85** [comment]
I am getting similar issue when I try to run/bundle my app using webpack. There error I'm getting is
```
Module not found: Error: Package path ./types is not exported from package path\to\node_modules\react-easy-crop (see exports field in path\to\node_modules\react-easy-crop\package.json)
```
This occurs when I add `"importsNotUsedAsValues": "preserve"` to my tsconfig compileOptions. This option is needed for webpack watch to detect changes in interface/type files.

It was happening in version 3.3.2 and when I upgraded to version 4.1.4

**Comment by ValentinH** [comment]
Indeed the exports file is missing the types file. Would you like to do a PR to fix this?

**Comment by ValentinH** [comment]
It should be fine in this file: https://github.com/ValentinH/react-easy-crop/blob/main/scripts/copy-build-files.js#L28

**Comment by Rc85** [comment]
@ValentinH It's beyond my knowledge unfortunately.

**Comment by Rc85** [comment]
@ValentinH Tried adding it to `exports` and got this error on compilation.
```
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export declare type Size = {
|     width: number;
|     height: number;
```

**Comment by ValentinH** [comment]
I think it's because it should be a `types` field as it's not a JS file.
Something like this probably (didn't try it)
```js
exports: {
      '.': {
        import: './index.module.js',
        require: './index.js',
      },
    "./types":  {
       types: './index.d.ts',
    },
    },
```

**Comment by Rc85** [comment]
Isn't this the same?
```
exports: {
  "./types": "./index.d.ts"
}
```
Update: If I use the subpaths (your suggested way), it still says module not found. If I use the above mentioned, it tells me I need an appropriate loader. And it's `types.d.ts` that it's being exported from.

**Comment by ValentinH** [comment]
I will do a change where the types will be exported from the index. This will be much simpler.

**Comment by ValentinH** [comment]
@Rc85  could you please try the version from #376.

You can install it by using `react-easy-crop@4.1.5--canary.376.4e31ef2.0`

**Comment by Rc85** [comment]
@ValentinH It's working now. No error.

**Comment by ValentinH** [comment]
Perfect! Let's release this!

**Comment by ValentinH** [comment]
The fix is available in https://github.com/ValentinH/react-easy-crop/releases/tag/v4.1.5

**Comment by vcarel** [comment]
Hi, I don't have a Typescript error on my end, but an eslint one (which is using typescript parser):

> Unable to resolve path to module 'react-easy-crop/types'. eslint([import/no-unresolved](https://github.com/import-js/eslint-plugin-import/blob/v2.26.0/docs/rules/no-unresolved.md))

I'm writing a comment in this thread because it sounds related.

**edit**: I'm on v4.2.0
**edit 2**: Forget my comment, the import should be without trailing "/types" now, e.g.: `import { Area } from "react-easy-crop"`
