### ISSUE TITLE
Final output to always be specific size (800 x 800)

### ISSUE THREAD

**Issue by plaporte** [ValentinH/react-easy-crop#375]
I absolutely cannot figure out how to set the final output to a specific size. I want it to always come out to 800px x 800px if it's larger than that. 

I figured that cropSize would do this, but it doesn't and I get errors like "[Error] croppedImage error: 
TypeError: Value NaN is outside the range [-2147483648, 2147483647]"

I've tried editing all kinds of things as well as the aspect ratio but cannot get this to work.

**Comment by ValentinH** [comment]
This issue should help you find a solution to your issue: https://github.com/ValentinH/react-easy-crop/issues/176

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
