### ISSUE TITLE
incorrect `croppedAreaPixels` when `restrictPosition` is true and original image is smaller than `cropSize`

### ISSUE THREAD

**Issue by convincee** [ValentinH/react-easy-crop#389]
**Describe the bug**
incorrect `croppedAreaPixels` when `restrictPosition` is `true` and original image is smaller than `cropSize`.
When `restrictPosition` is `false`, this issue won't exist.
 
**To Reproduce**
1. Go to https://codesandbox.io/s/patient-smoke-kxduw2
2. Click `choose file` to choose a image which is smaller than `cropSize` { width: 200, height: 100}
3. see the `width` or `height` of original image is always > `croppedAreaPixels`
**Expected behavior**
`width` and `height` of original image is always === `croppedAreaPixels`

**Comment by ValentinH** [comment]
From what I see the croppedAreaPixels width and height are matching the actual original size. I think this is the correct behavior.

To be transparent, I've never actually used the `cropSize` property and I believe it should be avoided.  See https://github.com/ValentinH/react-easy-crop/issues/186

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
