### ISSUE TITLE
React native mobile side

### ISSUE THREAD

**Issue by ShravanCentricwave** [ValentinH/react-easy-crop#391]
I can not install this lib in react native project, every time i got error.

If you can implement to allow this lib in react native project then it will be more better for react native community,
because, 'REACT JS' has mostly backend side and react native developers has frontend side. and this is so good for react native. 

when i do install then it will give me error like this every time, in your every version.
![01](https://user-images.githubusercontent.com/86836170/175468687-2fb543d6-6bef-4dd8-8da2-02bdf96d36bd.png)

There are libs for react native crop image for "React Native"
1. https://www.npmjs.com/package/react-native-image-crop-picker
2. https://www.npmjs.com/package/react-native-image-crop-tools

Here in this lib they provide cropping direct in gallery of mobile not in the application where developers will implement

Also we can not get cropx, cropy, cropheight, cropwidth, zoom in this lib, so we need that.

**Comment by ValentinH** [comment]
This library is for react-dom, react-native is a different platform. There is now way to have react-easy-crop working in it, it would require a completely different approach regarding renderer éléments, styling and events.
