### ISSUE TITLE
onCropComplete returns wrong coordinates for croppedAreaPixels

### ISSUE THREAD

**Issue by emmaGblt** [ValentinH/react-easy-crop#395]
**Describe the bug**
I have a basic cropper setup and it used to work well but since yesterday, when I move the grid, I get the following croppedAreaPixels:
{width: 932, height: 932, x: -8447, y: NaN}

So when I try to get the cropped image it doesn't work.

**To Reproduce**
1. Go to this [codesandbox](https://codesandbox.io/s/upbeat-zeh-903qxm?file=/src/App.js)
2. Move the grid
3. See the croppedAreaPixels displayed in the console

**Expected behavior**
Expecting onCropComplete to return numbers for x and y coordinates.

**Comment by ValentinH** [comment]
I had a hard time understanding what what the issue but it turns out it was a simple mistake 😅 .

You need:
```js
 const [crop, setCrop] = useState({ x: 0, y: 0 })
```

instead of:
```js
 const [crop, setCrop] = useState({ x: "0", y: "0" })
```
😄

**Comment by emmaGblt** [comment]
This indeed solved the problem ! Thanks a lot for your answer and sorry for the mistake.

**Comment by ValentinH** [comment]
You are welcome! Have fun 👋
