### ISSUE TITLE
Two finger drag broken with createElement

### ISSUE THREAD

**Issue by WalkToFreedom** [ValentinH/react-easy-crop#399]
**Describe the bug**
So this was a strange one, that had me scratching my head for a long time. I had an existing App that was rendering the App like so, and everything was working fine:

`  ReactDOM.render(
    <React.StrictMode>
      <App />
    </React.StrictMode>,  
    document.getElementById("root")
  );`

Then I created a new app with create-react-app, and it created it like so, which broke the two finger drag (my App is for touch screen); I could only drag with one finger:

`const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(
  <React.StrictMode>
      <App />
  </React.StrictMode>
);`

**To Reproduce**
Create app with create-react-app

**Expected behavior**
Be able to two finger drag, scale rotate etc. In terms of usability, having to one finger drag then scale rotate is very clumsy on a touch device.

**Comment by ValentinH** [comment]
Thanks for this issue.
I suspect it could be related to the react version. What version are you using on each app?
Also could you provide a codesandbox showing the issue please?

**Comment by WalkToFreedom** [comment]
Hi Valentin. Firstly, apologies for not saying thanks for the great software :)

Yes, it's definitely related to the react version. I believe the problem is: 
https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

Meaning it works in 17 but not 18

Sandbox [here](https://codesandbox.io/s/flamboyant-knuth-8n5hqm?file=/src/index.js)

**Comment by ValentinH** [comment]
Thanks for the sandbox, I'll investigate ASAP as it's both an important issue and also an interesting one. I'm really curious to understand what are we doing wrong that stopped working with React 18 😅

I suspect it would be related to [Automatic batching](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#automatic-batching).

**Comment by ValentinH** [comment]
I'm still on the phone so not yet able to try it but I think that these 2 callbacks are now batched and the second one overwrites the first:
- https://github.com/ValentinH/react-easy-crop/blob/main/src/Cropper.tsx#L422
- https://github.com/ValentinH/react-easy-crop/blob/main/src/Cropper.tsx#L522

We actually have a Cypress test for this "move with pinch" interaction [here](https://github.com/ValentinH/react-easy-crop/blob/main/cypress/integration/touch_spec.js#L62) so it will be interesting if it also catches the issue after upgrading.

**Comment by WalkToFreedom** [comment]
👏 Tested working. Thanks for fixing!
