### ISSUE TITLE
hello. Is there a way to add some anchors to crop area in order to obtain a resizable crop area? I know we have that cropSize prop, but can we add anchors for scaling that crop area similar with the ones iphone has when resizing an image? 

### ISSUE THREAD

**Issue by danarosca** [ValentinH/react-easy-crop#402]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- If you have ideas how to implement your new feature, please share!

- If you know any examples online that already implement such functionality, please share a link.

**Comment by ValentinH** [comment]
This is not possible and this is actually not the philosophy of this library.
What you are looking for is done by https://www.npmjs.com/package/react-image-crop 🙂
