### ISSUE TITLE
Bug on iOS (output is different from cropped section)

### ISSUE THREAD

**Issue by emmaGblt** [ValentinH/react-easy-crop#407]
Hi, thanks for your library ! I'm currently having a problem on iOS (Safari but also Chrome and Firefox). It works fine on my Ubuntu machine (Chrome and Firefox) so I didn't notice it at first.

**Describe the bug**
The returned cropped image is different from the cropped section of the original image on iOS.

When I log the output coordinates, I get the same results on both OS.

https://codesandbox.io/s/react-easy-crop-bug-on-ios-r5lnzi

1. Open this sandbox example on Safari
2. Select an image
3. Crop it (you can use the zoom feature)

**Observed behaviour:** The output image is different from the cropped section.
**Expected behaviour:**  Display the cropped section in the ouput img tag.

**Comment by ValentinH** [comment]
Hi, I don't have an iOS device. Could you please share a screenshot of the observer behaviour please and a one of the expected one?

**Comment by emmaGblt** [comment]
Sure !

**The cropped section**
![cropping](https://user-images.githubusercontent.com/109206059/187181214-ccf57f37-e131-4de8-a0df-2ce8df2ae660.png)

**The expected output** (what I get on Ubuntu)
![expected output (Ubuntu)](https://user-images.githubusercontent.com/109206059/187181690-d0719809-f4af-41c7-94f7-ae75c838e24d.png)

**What I get on iOS**
<img width="167" alt="wrong output (iOS)" src="https://user-images.githubusercontent.com/109206059/187181457-6cff945a-75ce-431d-ab9e-c51d206314fa.png">

**Comment by ValentinH** [comment]
I see that you are using a different `getCroppedImage` function than on [this example](https://codesandbox.io/s/q8q1mnr01w?file=/src/cropImage.js). Do you also observe the same issue on this example?

**Comment by emmaGblt** [comment]
No, it works well on Safari. I guess it comes from my function then... I had to modify it because I don't need rotation, I need to be able to zoom out and I was unable to adapt the function from the example.

**Comment by ValentinH** [comment]
OK I see 🙂 

I'm closing this issue as the canvas logic is outside the scope of this library. To be transparent, this kind of cross-browsers issues with canvas is exactly why the "canvas cropping" logic is provided only as an example and not inside the library: too hard to maintain 😅
