### ISSUE TITLE
Upload Base64 video and return cropped Base64 (3MB)

### ISSUE THREAD

**Issue by ravis-farooq** [ValentinH/react-easy-crop#408]
Your video cropper is working fine but feature that is missing in that is if we pass video most probably of 3MB, it should return the cropped video, which we can upload then to the third party service such as minio, cloudinary etc.

**Comment by ValentinH** [comment]
This library is only providing the cropping UI, not the actual cropping logic to modify the image or video.

As explained in https://github.com/ValentinH/react-easy-crop/discussions/361, I don't think this is anyway doable in the browser.
