### ISSUE TITLE
crop area becomes smaller

### ISSUE THREAD

**Issue by Cikayo** [ValentinH/react-easy-crop#409]
It is normal for the first operation.
![image](https://user-images.githubusercontent.com/41409542/190353590-885dcc5a-571d-4881-a704-fa8d9d91c7bc.png)

However, there is a problem with the second operation.
![image](https://user-images.githubusercontent.com/41409542/190353749-15af8522-90ed-4f29-9eb6-08af6091ab43.png)

I need your help.Thanks!

**Comment by ValentinH** [comment]
What is different between the two cases? Could you please share a codesandbox showing the issue?

**Comment by Cikayo** [comment]
> What is different between the two cases? Could you please share a codesandbox showing the issue?

Here is my code.
https://codesandbox.io/s/suspicious-ishizaka-fquxnh?file=/src/App.js

After selecting an image for the first time, click `Cancel`. Problem selecting another image the second time.

**Comment by ValentinH** [comment]
I'm not fully getting why this is happening but it seems to be related with the way `antd-modal` hides its content when the modal is closed.

I managed to fix it by not rendering the modal at all if `imageUrl` is empty:
![image](https://user-images.githubusercontent.com/2678610/190437418-a46e4266-473a-47a2-a4f8-6a09c1c7928d.png)

and reset it on cancel:
![image](https://user-images.githubusercontent.com/2678610/190437497-55bcef57-86f5-4ceb-b9f1-19b1b6a9aae7.png)

Here's a working sandbox:
https://codesandbox.io/s/blissful-zeh-tur30j?file=/src/App.js

**Comment by Cikayo** [comment]
Wow! It's working. Thanks!

At first, I thought it was the component `Cropper` that cached the `image`. And try the code. I'm going in the wrong direction.

![image](https://user-images.githubusercontent.com/41409542/190524551-4fc3fda0-00eb-4508-9cbb-e5a3fe93ab11.png)

Thank you again for your help.

**Comment by ValentinH** [comment]
Yes this is also the first thing I tried as there are often issues when the Cropper is rendered outside of screen. For example, when  a modal is closed but its content isn't unmounted.

**Comment by ValentinH** [comment]
If you don't want to fully unmount the modal when it's just supposed to be closed, you can have a look to #267. You might have some luck there as the author was using the `Modal` from `antd` (dont know how similar it is to `antd-mobile` `Mask`).
