### ISSUE TITLE
mediaSize width and height are 0 for images larger than the container area

### ISSUE THREAD

**Issue by beneficialmedia** [ValentinH/react-easy-crop#416]
**Describe the bug**
The `mediaSize` `width` and `height` are `0`, but the `naturalWidth` and `naturalHeight` reflect the correct width and height of the file only when the file width and height is larger than the easy crop container width and height. 

**To Reproduce**
Not sure if it’s my implementation, but pretty sure it’s good. I’m using React 17 and TypeScript.

here’s the code to repro (Will update with CodeSandbox url when I’m back at my laptop)

```
import React, { useState, useCallback } from "react";
import Slider from "@material-ui/core/Slider";
import Cropper from "react-easy-crop";
import { Point, Area } from "react-easy-crop/types";
import "./styles.css";

const App = () => {
  const [crop, setCrop] = useState<Point>({ x: 0, y: 0 });
  const [zoom, setZoom] = useState(1);
  const [cropSize, setCropSize] = useState<Size>({ width: 0, height: 0 });
  
  const aspect = 1;

  const onMediaLoaded = useCallback(
    (mediaSize) => {
      const { width, height } = mediaSize;
      const ratioWidth = height * aspect;

      if (width > ratioWidth) {
        setCropSize({ width: ratioWidth, height });
      } else {
        setCropSize({ width, height: width / aspect });
      }
    },
    [aspect]
  );
  
  const onCropComplete = useCallback(
    (croppedArea: Area, croppedAreaPixels: Area) => {
      console.log(croppedArea, croppedAreaPixels);
    },
    []
  );

  return (
    <div className="App">
      <div className="crop-container">
        <Cropper
          image="https://img.huffingtonpost.com/asset/5ab4d4ac2000007d06eb2c56.jpeg?cache=sih0jwle4e&ops=1910_1000"
          crop={crop}
          cropSize={cropSize}
          zoom={zoom}
          aspect={aspect}
          onCropChange={setCrop}
          onCropComplete={onCropComplete}
          onMediaLoaded={onMediaLoaded}
          onZoomChange={setZoom}
        />
      </div>
      <div className="controls">
        <Slider
          value={zoom}
          min={1}
          max={3}
          step={0.1}
          aria-labelledby="Zoom"
          onChange={(e, zoom) => setZoom(Number(zoom))}
          classes={{ root: "slider" }}
        />
      </div>
    </div>
  );
};

export default App;
```

**Expected behavior**
The `width` and `height` should have the correct value.

**Comment by beneficialmedia** [comment]
@ValentinH lemme know if I can do anything to fix the above. What happens is the crop area renders as 0x0 pixels.

**Comment by dkilgore-eightfold** [comment]
Downgrading to v3.3.2 seems to have fixed the problem.

**Comment by ValentinH** [comment]
3.3.2! Thats a pretty old version!  Why did you try this one specifically?
I can't try to have a look to the issue if you can share z codesandbox.

**Comment by dkilgore-eightfold** [comment]
Here's the sandbox link. Looks to be related to css transform animation. Let's say a modal scales into view. The canvas doesn't like that I guess -->

https://codesandbox.io/s/react-easy-crop-in-ts-forked-7d6shp?file=/src/styles.css

**Comment by ValentinH** [comment]
Oh I get it now, are you trying to display the Cropper in a modal? If yes, there are several related issues. You can have a look to the latest one : #409

**Comment by ValentinH** [comment]
This answer could also be useful: https://github.com/ValentinH/react-easy-crop/issues/400#issuecomment-1195100037

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
