### ISSUE TITLE
What's a recommended way to style the `::before` and `after` pseudo elements of the Crop Area?

### ISSUE THREAD

**Issue by johndebord** [ValentinH/react-easy-crop#419]
I'm looking for a recommended way to style the `border` property of the `.reactEasyCrop_CropAreaGrid::before` and `.reactEasyCrop_CropAreaGrid::after` pseudo elements. I've tried changing up the `cropAreaStyle` property (https://github.com/ValentinH/react-easy-crop/blob/main/src/Cropper.tsx#L46), but with no success.

<img width="576" alt="sc" src="https://user-images.githubusercontent.com/35586806/200760981-b1cc5b78-8765-4be6-803b-36c414d17216.png">

**Comment by ValentinH** [comment]
I dont think that pseudo elements can be styled with style attributes. You should manage to do it using the `classes` property for the crop area. However, you might get specificity issues as the styles are applied on the grid class:
https://github.com/ValentinH/react-easy-crop/blob/main/src/styles.css#L56

Or directly set the global `reactEasyCrop_CropAreaGrid` class.

**Comment by johndebord** [comment]
Ok, thanks for the feedback
