### ISSUE TITLE
Cropper appears to not work when setting the `cropSize` property

### ISSUE THREAD

**Issue by johndebord** [ValentinH/react-easy-crop#421]
I'm trying to set the `cropSize` property the same as the container's size.

When I attempt to do this using a reference the `Cropper` as a whole appears to not work.

I can't move the cropper around, or zoom in/out, and the white space (to the right of the image) is inconveniently visible.

Not sure where to go from here.

```javascript
<Cropper
  aspect={1}
  crop={stCrop}
  cropSize={{
    height:
    refCropper.current !== null
      ? refCropper.current.containerRect.height
      : 0,
    width:
    refCropper.current !== null
      ? refCropper.current.containerRect.width
      : 0,
  }}
  image={stAppState.content.content}
  onCropChange={setStCrop}
  onCropComplete={onCropComplete}
  onZoomChange={setStZoom}
  ref={refCropper}
  zoom={stZoom}
/>
```

<img width="333" alt="image" src="https://user-images.githubusercontent.com/35586806/201229099-294c0f59-3703-4cb2-8cd8-dd76dff7d089.png">

**Comment by ValentinH** [comment]
To be honest, I've never used the `cropSize` prop. I'm not sure how people are using it but I'm sometimes willing to just remove it.

What is your use case? Do you really need to use `cropSize` instead of just relying on `aspect`?

**Comment by johndebord** [comment]
Right, I think the `cropSize` prop introduced more complexity for me than needed.

Strictly relying on the `aspect` prop definitely helped clear things up.

I ended up solving the issue, but it took modifying some of the source.

Not entirely sure if I'm doing something backwards, so I can't judge if adding styles and a new option to `objectFit` would be PR-worthy.

I'll document it here in case someone has the same problem in the future. 

```javascript
<Box
  sx={{
    "& .reactEasyCrop_Cover_Horizontal": {
      height: "100%",
      width: "auto",
    },
    "& .reactEasyCrop_Cover_Vertical": {
      height: "auto",
      width: "100%",
    },
    height: "calc(100vw - 2rem)",
    position: "relative",
  }}
>
  <Cropper
    aspect={1}
    crop={stCrop}
    image={stAppState.content.content}
    objectFit={"auto-cover"}
    onCropChange={setStCrop}
    onZoomChange={setStZoom}
    zoom={stZoom}
  />
</Box>
```

```diff
case "auto-cover":
  renderedMediaSize =
    naturalWidth > naturalHeight
    ? {
-     width: _this.containerRect.width,
-     height: _this.containerRect.width / mediaAspect,
+     width: _this.containerRect.width * mediaAspect,
+     height: _this.containerRect.height,
    }
    : {
-     width: _this.containerRect.height * mediaAspect,
-     height: _this.containerRect.height,
+     width: _this.containerRect.width,
+     height: _this.containerRect.height / mediaAspect,
    };
  break;
```

<img width="333" alt="image" src="https://user-images.githubusercontent.com/35586806/201462824-9ba46aa6-14fc-4fd2-a552-8797b4125ac0.png">

**Comment by ValentinH** [comment]
Ok this confirms my opinion about `cropSize` 😅

So basically, you reversed the logic for the auto-cover, didn't you? Could you share why did you have to do this? If this is a generic use case, I'm ok to accept a new option to `objectSize`.

**Comment by johndebord** [comment]
Yeah, so I reversed the logic for auto-cover because the cropper/image weren't taking up the full size of the container.

The default behavior for auto-cover seems to be that the cropper covers the image, but at the same time, the cropper/image aren't the same size of the container.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/35586806/201497167-38f6668a-1bc5-4bc7-8ce8-83f1f43b5d78.png">

**Comment by ValentinH** [comment]
I'm wondering if the issue is because`auto-cover` was added with landscape images in mind. 
We might reverse it when the image is portrait. To do so, we could add the same condition that the one use in `contain`: `containerAspect > mediaAspect`.

What do you think?

**Comment by johndebord** [comment]
> I'm wondering if the issue is because `auto-cover` was added with landscape images in mind.
> We might reverse it when the image is portrait. To do so, we could add the same condition that the one use in `contain`: `containerAspect > mediaAspect`.

Yeah, that's probably reason & that sounds good to me

**Comment by ValentinH** [comment]
I'm AFK for a few days, but I'll try to play with this when I'm back.

**Comment by ValentinH** [comment]
Unless you are willing to do a PR for this, which I could merge and release from the phone if it works fine.

**Comment by johndebord** [comment]
> We might reverse it when the image is portrait. To do so, we could add the same condition that the one use in `contain`: `containerAspect > mediaAspect`.

Just tested this out. Unless I'm missing something, it doesn't provide the fix. The image doesn't fill the entire container. So, I think, in order to solve this, a new option has to be added (with an additional CSS styles class as well)

**Comment by ValentinH** [comment]
I think the new condition should also be applied here to flip the class: https://github.com/ValentinH/react-easy-crop/blob/main/src/Cropper.tsx#L719
