### ISSUE TITLE
`auto-cover` not working in React Bootstrap Modal

### ISSUE THREAD

**Issue by raffibag** [ValentinH/react-easy-crop#423]
**Describe the bug**
When using `objectFit='auto-cover'` inside a React Bootstrap Modal, the cropper invariably seems to render images as `'horizontal-cover'`, regardless of the original image dimensions. I had originally thought this had something to do with the image source, which is being passed to the modal component as a state, but the issue persists even after clearing the image select input and the state on modal close. I have a similar issue when using the manual logic of `objectFit={ width > height ? 'vertical-cover' : 'horizontal-cover' }`.

I'm thinking there may be some state setting that is not updating and that I'm unable to reset / clear on modal close. Is it possible to "reset" the Cropper component on state change or on modal close?

**To Reproduce**
1. With component's `objectFit` prop set to `'auto-cover'`, select a landscaped image (i.e., where width > height);
2. Image loads in Cropper as `'horizontal-cover'`

**Expected behavior**
1. With component's `objectFit` prop set to `'auto-cover'`, select a landscaped image (i.e., where width > height);
2. Image should load in Cropper as `'vertical-cover'` (excess clearspace below the image - see attached screen)

Here's the codesandbox. You can edit the `objectFit` prop in the `InputProfileModal.js` file. You'll note that when `'vertical-cover'` or `'horizontal-cover'` are used explicitly, the expected results are rendered.

Edit: Of course, I would be remiss if I weren't to say: great library! 

https://codesandbox.io/s/react-bootstrap-modal-react-easy-crop-en0obm?file=/src/InputProfileModal.js

![Screen Shot 2022-11-20 at 10 32 17 AM](https://user-images.githubusercontent.com/2711689/202919555-fd44454a-6f85-4a86-b99f-4a96bbdc61a1.png)

**Comment by ValentinH** [comment]
Thanks for the clear issue. I'm currently away from my computer so I'm not able to debug this at the moment. However, I can provide a hint maybe: there were several other issues related to the Cropper being displayed inside a modal. The key to fix them was to ensure the Cropper isn't initialised before the modal us fully open. Otherwise, any sizing computing are incorrect as the parent container doesn't have the real size yet.

**Comment by raffibag** [comment]
Thanks, Valentin! While your hint did, indeed help, the `'auto-cover'` issue persists. See updated code: https://codesandbox.io/s/react-bootstrap-modal-react-easy-crop-en0obm

I was able to get it working using a ternary contained within an `img.onload` function wrapped within a `useEffect` hook. This gives the modal time to reliably get the image dimensions prior to rendering the Cropper component.

While this workaround technically resolves the issue, I'll defer to you whether or not it warrants closing. Thanks again!

**Comment by ValentinH** [comment]
Thanks for the details. Let's keep this open, I'll try to have a look when I'm back to see if this could have been automatically handled by the library.

**Comment by ivnsch** [comment]
I'm experiencing this too, on a plain next.js app and not a modal. Version 4.6.3.

**Comment by ValentinH** [comment]
Please share a codesandbox showing the issue.

**Comment by adammo94** [comment]
Same here, custom modal, next.js app, not working, 4.6.3 version.

**Comment by ValentinH** [comment]
Please share a codesandbox showing the issue.

**Comment by adammo94** [comment]
I tried to, however we have a ton of additional code I'd have to separate. However I probably found the problem, when I wrap Cropper inside div that has position relative then the problem occurs.

**Comment by ValentinH** [comment]
The thing is that you actually should use a relative parent unless you want the cropper to be fullscreen:
![image](https://user-images.githubusercontent.com/2678610/217237285-53920ef3-1fe1-413f-9e5b-5267d482836c.png)

**Comment by ValentinH** [comment]
For the moment, with not reproduction, I'm going to close this issue. When it comes to modal, I already shared above what needs to be taken into account for this to work. I don't see much that can be done as part of the library.
