### ISSUE TITLE
Is there way to change Crop style?

### ISSUE THREAD

**Issue by JudisDev** [ValentinH/react-easy-crop#433]
Is there any way to change the crop style to resize the area instead of dragging the image?

Picture for reference:   
<img src="https://user-images.githubusercontent.com/104455724/208152711-b7651e58-7cb2-47bd-b34d-b03e043ae38e.png" width="500"/>

**Comment by ValentinH** [comment]
No this is not possible to have such a result. It looks like you should try https://www.npmjs.com/package/react-image-crop instead.

**Comment by JudisDev** [comment]
Ok, Thanks!
