### ISSUE TITLE
How to use it with touch devices?

### ISSUE THREAD

**Issue by andreisucman** [ValentinH/react-easy-crop#434]
I suppose the onTouchRequest prop is meant to make the cropper suitable for use on touch devices? But how to do that? Can you please suggest an implementation?

Snippets are welcome. :)

**Comment by andreisucman** [comment]
My issue was related to Firefox. It's emulator doesn't work on touch devices, but chrome does.

**Comment by ValentinH** [comment]
Indeed, there should be nothing in particular to support touch devices. It works out.of the box.
