### ISSUE TITLE
Picture not in the middle of the cropper when ZOOM < 1

### ISSUE THREAD

**Issue by gybeasmz** [ValentinH/react-easy-crop#435]
Hello, I want to give users the option to shrink their picture to better fit inside the crop area if needed. However the picture gets aligned to the upper left corner as soon as it gets smaller than the crop area. I want to override this behaviour, so it always stays centered, BECAUSE IT´S NOT POSSIBLE TO DRAG IT to the desired place once it gets smaller.

Thanks in advance for your answer,
Matt.

**Comment by ValentinH** [comment]
Sorry for the late answer ! 

This can actually be done outside of the library. See this example: https://codesandbox.io/s/adoring-bardeen-qxybeb?file=/src/index.js

You can control the value of the `crop` state depending on the `zoom` one.

**Comment by gybeasmz** [comment]
Brilliant. Thank you!
