### ISSUE TITLE
Getting "Document is not defined" when using in Nextjs project

### ISSUE THREAD

**Issue by devnostic** [ValentinH/react-easy-crop#445]
**Describe the bug**
I am using just the Cropper element and it is giving me a "document is not defined" error in  my nextjs project. is there something additional i need to do to configure this project?

**Comment by ValentinH** [comment]
I suspect https://github.com/ValentinH/react-easy-crop/releases/tag/v4.5.1 being the issue. Could you please try version `4.5.0` and let me know if it works for you? If yes, we can easily add a fix I think.

**Comment by devnostic** [comment]
I am using "react-easy-crop": "^4.7.0",

I actually fixed it by putting <Cropper into a component and then dynamically including it 

const ImageCropper = dynamic(() => import('components/reuseable/image-cropper'), { ssr: false })

**Comment by ValentinH** [comment]
Could you quickly try with the above mentioned version ?
