### ISSUE TITLE
Add polygon crop shape

### ISSUE THREAD

**Issue by husainasfak** [ValentinH/react-easy-crop#447]
It is the best tool for cropping images and videos in react. But now, it has only two crop shape rectangle and circle. if we can add more shapes like polygon or rectangle with border radius then I will be more flexible

**Comment by ValentinH** [comment]
This can actually be achieved with CSS by using the `reactEasyCrop_CropArea` class.

See this example: https://codesandbox.io/s/suspicious-monad-9zvy4u?file=/src/styles.css

**Comment by ashfaqhussain26** [comment]
I change crop shape to round but I am getting output in rectangle. How can I fix this @ValentinH

**Comment by ValentinH** [comment]
The output logic is not handled inside this library. It needs to be done using canvas operations. This is where you can add specific logic to make the output rounded.

**Comment by ashfaqhussain26** [comment]
I tried to create round output

export const createImage = (url) =>
     new Promise((resolve, reject) => {
          const image = new Image();
          image.addEventListener("load", () => resolve(image));
          image.addEventListener("error", (error) => reject(error));
          image.setAttribute("crossOrigin", "anonymous"); // needed to avoid cross-origin issues on CodeSandbox
          image.src = url + "?" + new Date().getTime();
     })

export function getRadianAngle(degreeValue) {
     return (degreeValue * Math.PI) / 180
}

/**
 * Returns the new bounding area of a rotated rectangle.
 */
export function rotateSize(width, height, rotation) {
     const rotRad = getRadianAngle(rotation)

     return {
          width:
               Math.abs(Math.cos(rotRad) * width) + Math.abs(Math.sin(rotRad) * height),
          height:
               Math.abs(Math.sin(rotRad) * width) + Math.abs(Math.cos(rotRad) * height),
     }
}

export default async function getCroppedImgRound(
     imageSrc,
     pixelCrop,
     cropRadius
) {
     console.log(pixelCrop,
          cropRadius)
     const image = await createImage(imageSrc)
     const canvas = document.createElement('canvas')
     const ctx = canvas.getContext('2d')

     if (!ctx) {
          return null
     }
     canvas.width = pixelCrop.width
     canvas.height = pixelCrop.height

     ctx.save();
     ctx.beginPath()
     ctx.arc(cropRadius, cropRadius, cropRadius, 0, 2 * Math.PI)
     ctx.closePath();
     ctx.clip()

     const scaleX = image.naturalWidth / image.width
     const scaleY = image.naturalHeight / image.height
     const originX = pixelCrop.x * scaleX
     const originY = pixelCrop.y * scaleY
     const finalWidth = pixelCrop.width * scaleX
     const finalHeight = pixelCrop.height * scaleY
     const xOffset = (finalWidth - cropRadius * 2) / 2
     const yOffset = (finalHeight - cropRadius * 2) / 2

     ctx.drawImage(
          image,
          originX + xOffset,
          originY + yOffset,
          cropRadius * 2,
          cropRadius * 2,
          0,
          0,
          cropRadius * 2,
          cropRadius * 2
     )

     ctx.restore();
     return new Promise((resolve) => {
          canvas.toBlob((file) => {
               console.log(URL.createObjectURL(file))
               resolve(URL.createObjectURL(file))
          }, 'image/jpeg')
     })
}


but this solution giving me circular image but behind it there is black rectangle. How can i fixed this any idea?

**Comment by ashfaqhussain26** [comment]
I tried to create round output

```
export const createImage = (url) =>
     new Promise((resolve, reject) => {
          const image = new Image();
          image.addEventListener("load", () => resolve(image));
          image.addEventListener("error", (error) => reject(error));
          image.setAttribute("crossOrigin", "anonymous"); // needed to avoid cross-origin issues on CodeSandbox
          image.src = url + "?" + new Date().getTime();
     })

export function getRadianAngle(degreeValue) {
     return (degreeValue * Math.PI) / 180
}

/**
 * Returns the new bounding area of a rotated rectangle.
 */
export function rotateSize(width, height, rotation) {
     const rotRad = getRadianAngle(rotation)

     return {
          width:
               Math.abs(Math.cos(rotRad) * width) + Math.abs(Math.sin(rotRad) * height),
          height:
               Math.abs(Math.sin(rotRad) * width) + Math.abs(Math.cos(rotRad) * height),
     }
}

export default async function getCroppedImgRound(
     imageSrc,
     pixelCrop,
     cropRadius
) {
     console.log(pixelCrop,
          cropRadius)
     const image = await createImage(imageSrc)
     const canvas = document.createElement('canvas')
     const ctx = canvas.getContext('2d')

     if (!ctx) {
          return null
     }
     canvas.width = pixelCrop.width
     canvas.height = pixelCrop.height

     ctx.save();
     ctx.beginPath()
     ctx.arc(cropRadius, cropRadius, cropRadius, 0, 2 * Math.PI)
     ctx.closePath();
     ctx.clip()

     const scaleX = image.naturalWidth / image.width
     const scaleY = image.naturalHeight / image.height
     const originX = pixelCrop.x * scaleX
     const originY = pixelCrop.y * scaleY
     const finalWidth = pixelCrop.width * scaleX
     const finalHeight = pixelCrop.height * scaleY
     const xOffset = (finalWidth - cropRadius * 2) / 2
     const yOffset = (finalHeight - cropRadius * 2) / 2

     ctx.drawImage(
          image,
          originX + xOffset,
          originY + yOffset,
          cropRadius * 2,
          cropRadius * 2,
          0,
          0,
          cropRadius * 2,
          cropRadius * 2
     )

     ctx.restore();
     return new Promise((resolve) => {
          canvas.toBlob((file) => {
               console.log(URL.createObjectURL(file))
               resolve(URL.createObjectURL(file))
          }, 'image/jpeg')
     })
}
```
but this solution giving me circular image but behind it there is black rectangle. How can i fixed this any idea?

**Comment by ValentinH** [comment]
First thing that you should probably change is the output format: replace `'image/jpeg'` by `'image/png'`.

**Comment by ashfaqhussain26** [comment]
Hey it works. Thanks a lot.
