### ISSUE TITLE
Crop size is not calculated correctly

### ISSUE THREAD

**Issue by khuongtp** [ValentinH/react-easy-crop#453]
**Describe the bug**
Cropsize width is not calculated correctly
![image](https://user-images.githubusercontent.com/62872729/226789696-620e6c7b-350c-4f37-9131-7e5a3023edc2.png)
Cropper is inside of chakra-ui modal btw.
But when I resize chrome viewport, it works
![image](https://user-images.githubusercontent.com/62872729/226790055-38d6ef76-48ab-45c2-abd2-df9397dc585c.png)

**Expected behavior**
Cropsize width should take up all available space so that user can capture the whole width of the image

**Comment by ValentinH** [comment]
This is a known issue when displaying the Cropper inside a modal
 Unfortunately, there isn't much we can do as part of the lib (unless someone proves me wrong).

You can have a look to similar issues such as #400 for workarounds.

**Comment by khuongtp** [comment]
Thank you, I'll take a look
