### ISSUE TITLE
Inconsistent crop window size

### ISSUE THREAD

**Issue by AppleJem** [ValentinH/react-easy-crop#454]
**Describe the bug**
Given a constant parent element size, the size of the crop window (be it circle or rectangular) changes based on whether the images fits the parent container

**To Reproduce**
1. Go to the example: https://codesandbox.io/s/q8q1mnr01w
2. Change the link address to a photo that's of a different aspect ratio. 
Eg. https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/%D0%AF%D0%B9%D1%86%D0%B0_%D0%B2%D1%81%D0%BC%D1%8F%D1%82%D0%BA%D1%83_%D0%B8%D0%BB%D0%B8_%D0%B4%D0%B5%D0%BD%D0%B0%D1%82%D1%83%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D0%B0%D0%BB%D1%8C%D0%B1%D1%83%D0%BC%D0%B8%D0%BD%D0%B0.jpg/500px-%D0%AF%D0%B9%D1%86%D0%B0_%D0%B2%D1%81%D0%BC%D1%8F%D1%82%D0%BA%D1%83_%D0%B8%D0%BB%D0%B8_%D0%B4%D0%B5%D0%BD%D0%B0%D1%82%D1%83%D1%80%D0%B0%D1%86%D0%B8%D1%8F_%D0%B0%D0%BB%D1%8C%D0%B1%D1%83%D0%BC%D0%B8%D0%BD%D0%B0.jpg

4. You can now see that the crop box isn't the right size (no longer fills vertical height) because it's adjusting to the image
**Expected behavior**

I believe this is caused by the image initially having something like the CSS property `object-fit:contain` (just as an analogy)

**Comment by ValentinH** [comment]
It seems that the image you shared in 2. is the same than the one used in the 1. sandbox. Did you overwrite the sandbox?

**Comment by AppleJem** [comment]
> It seems that the image you shared in 2. is the same than the one used in the 1. sandbox. Did you overwrite the sandbox?

My apologies, I meant to use the link from the original example, just updated the issue

**Comment by ValentinH** [comment]
Thanks.

I think you can actually use the `objectFit` property available on the cropper to control how the image is adjusted to the container. `auto-cover` or `vertical-cover` should be what you are looking for.

**Comment by AppleJem** [comment]
Oh I think it is! Thank you 👍
