### ISSUE TITLE
Feature Request: objectFit: auto-contain, but the other way around

### ISSUE THREAD

**Issue by KostyaNazvanov** [ValentinH/react-easy-crop#464]
Currently objectFit: auto-contain fits the image by its longer side.
In my case I would like to fit image by shorter side, so it always covers the whole space

vertical-cover or horizontal-cover works exactly as I need, but it requires manual calculations to decide which cover to use.

Current behavior:
![image](https://github.com/ValentinH/react-easy-crop/assets/66772227/d0d494d9-3a17-4134-a1bb-a360e67e7183)

Would like a feature to get this behavior:
![image](https://github.com/ValentinH/react-easy-crop/assets/66772227/4b485ada-6424-4762-a6ba-2e7995868113)

**Comment by ValentinH** [comment]
Did you try the `auto-cover` option?

**Comment by KostyaNazvanov** [comment]
Yes, `auto-cover` fits the image by longer side as well, but it's vertically centered.

![image](https://github.com/ValentinH/react-easy-crop/assets/66772227/5b1deb33-43de-48d1-a21a-1327698ba456)

Would be great to have a prop like `fitSideMode: longSide | shortSide` or add option to `objectFit: fill`

**Comment by ValentinH** [comment]
I think I get the idea but I struggle to see the expected behavior on your example image. Could you highlight where the image borders are please?

**Comment by KostyaNazvanov** [comment]
I made background red to visually separate it from the image I try to upload.
Basically, right now any wide or high image is fully fit into the view without overflowing it.
I'm looking for an option to fill whole view with the image, ignoring the overflow

For my wide image vertical-cover does what I expect.

Current behavior: auto-cover
![image](https://github.com/ValentinH/react-easy-crop/assets/66772227/6b66e351-60f1-47c5-8da8-768128739336)

Expected: similar to vertical-cover, but automatically detects which side is longer
![image](https://github.com/ValentinH/react-easy-crop/assets/66772227/7051e181-0bcb-4495-8271-e55a55984da4)

**Comment by KostyaNazvanov** [comment]
but vertical cover won't work for long image
![image](https://github.com/ValentinH/react-easy-crop/assets/66772227/d9ad4049-8715-451a-952a-0adf446123ab)

I have to manually change objectFit to horizontal-cover. now it fills whole view again
![image](https://github.com/ValentinH/react-easy-crop/assets/66772227/cb340beb-fc51-45fb-90ba-f2026510cb32)

**Comment by KostyaNazvanov** [comment]
I guess someone made a PR with the thing I look for. What a blessing :)
https://github.com/ValentinH/react-easy-crop/pull/466

**Comment by kruchkou** [comment]
Hi All!

That should be exactly what I was looking for and achieved in the [PR](https://github.com/ValentinH/react-easy-crop/pull/466) here
You could also take a look at the [sandbox](https://codesandbox.io/s/react-easy-crop-forked-7is1hm) to see live example
