### ISSUE TITLE
getCroppedImg returning undefined on IOS

### ISSUE THREAD

**Issue by alonazisser** [ValentinH/react-easy-crop#468]
**Describe the bug**
After cropping the image and running the getCroppedImg() function, an "undefined" error is received.

**To Reproduce**
1. Go to https://lapromesse.co.il/configurator/?framing_type=digital on IOS
2. on the "Recommended Size:" area, choose a square size and a cropping panel will open.
4. set the crop area wherever you like and click "crop" at the top button.
3. You will get the error on an alert (may take a few seconds).

**Expected behavior**
The URL of the image should be retrieved after the getCroppedImg() and placed in the top area of the configurator inside the frame.

**Comment by ValentinH** [comment]
What `getCroppedImg` function are you using?

**Comment by alonazisser** [comment]
As I see on the function comments: https://github.com/DominicTobias/react-image-crop

**Comment by ValentinH** [comment]
This is not the same package so I don't know about how these functions evolved there. 
I recommend to use the one from this file: https://codesandbox.io/s/q8q1mnr01w?file=/src/cropImage.js

**Comment by alonazisser** [comment]
@ValentinH 
Yes, this is the one. if you look on line 29 on the comment: "This function was adapted from the one in the ReadMe of https://github.com/DominicTobias/react-image-crop".

I am using the code this way:

importing it from my utils folder:
`import getCroppedImg from "./utils/cropImage";`

using it on the code:

`  const { file, url } = await getCroppedImg(
        photoAttributes.src, //this value is the image src from the state//
        cropData,
        0
  );`
  
  This is working perfectly on all devices except IOS.

**Comment by ValentinH** [comment]
Are you using this exact latest version?

**Comment by alonazisser** [comment]
@ValentinH 
It wasn't the latest version, I have updated it but still receiving the same error.

**Comment by ValentinH** [comment]
What error do you get? 
I I recall correctly, the way to avoid issues on iOS is to limit the Canvas size.

**Comment by alonazisser** [comment]
@ValentinH 

I get "undefined".
Do you mean changing the canvas width and height? tried this way and it didn't help:

` canvas.width = 500;
 canvas.height = 500;`

**Comment by ValentinH** [comment]
I meant: do you get an error?

**Comment by alonazisser** [comment]
seems that the src I am sending to the getCroppedImg() function is undefiend.
At first, I thought that it is something to do with the variable I am getting from the reducer: `photoAttributes.src`, But then I tried to add a hardcoded url to an image on the server and the response is still "undefiend". 

Any ideas on why the src is not being passed to the function?

**Comment by ValentinH** [comment]
There is too much external logic to this library in what you are describing. Without a codesandbox reproducing the exact issue you are facing, I'll not be able to help further.

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉
