### ISSUE TITLE
Crop selections overlap

### ISSUE THREAD

**Issue by carlosdi0** [ValentinH/react-easy-crop#470]
Bug Description:

When performing the crop process on a PNG image multiple times using react-easy-crop, it results in generating a collage of images instead of correctly cropping the image.

Steps to Reproduce:
1. Load a PNG image into react-easy-crop.
2. Perform a crop on a specific part of the image and save it.
3. Reload the same image into react-easy-crop.
4. Perform a new crop on a different part of the image.
5. Save the second selection.
6. Observe how the two crop selections overlap, resulting in a collage of the images instead of proper cropping.

Attached Video:
I have attached a video demonstrating the bug in action.
[Codesandbox](https://codesandbox.io/s/react-easy-crop-custom-image-demo-forked-fp282q?file=/src/index.js:2442-2466)
[Link to the video](https://streamable.com/i32h0a)

Thank you so much for your hard work in developing this fantastic library. Keep up the excellent work!

**Comment by ValentinH** [comment]
Did you fix it since opening the issue? When I try the sandbox on my phone I'm not able to reproduce.

If not, what browser are you using?

**Comment by carlosdi0** [comment]
Hi Valentin, im using Coogle Chrome versión 114.0.5735.134.
It's weird because we are three fellow developers and one of us can't reproduce it either.
I will try to fix it, I will keep you informed.

Thx for al :)

**Comment by ValentinH** [comment]
Just tried on Brave/MacOS and I'm able to reproduce.
This is very weird. I tried a few things like resetting the canvas or filling it with black and it doesn't solve it.

**Comment by carlosdi0** [comment]
It seems to be a problem with the putImageData method. I will continue investigating and testing.

**Comment by carlosdi0** [comment]
> Did you fix it since opening the issue? When I try the sandbox on my phone I'm not able to reproduce.
> 
> If not, what browser are you using?

I pass you the pull request with the fix, I hope it is helpful, thank you very much!
[https://github.com/ValentinH/react-easy-crop/pull/472](https://github.com/ValentinH/react-easy-crop/pull/472)
