### ISSUE TITLE
Image size increases drastically after cropping

### ISSUE THREAD

**Issue by balajiradhakrish** [ValentinH/react-easy-crop#476]
**Describe the bug**
Image size increases drastically after cropping the image, observed this mostly happening for images captured using mobile phones.

**To Reproduce**
1. Take a photo using your mobile.
2. Crop the image using the npm
3. save the image
4. see that the image size increases

**Expected behavior**
The size of the image should be less than or equal to the original image size

**Comment by ValentinH** [comment]
What do you use for the "3. Save the image" step?
Indeed, the library doesn't include this logic, only a few examples are shared to show how it could be done in the browser or the server.

**Comment by balajiradhakrish** [comment]
we are using canvas, Thanks, will check and get back.

**Comment by anarkrypto** [comment]
Using canvas too, a 5MB image increased to 39MB !!!

Now I am resizing with this code: https://github.com/ValentinH/react-easy-crop/issues/176#issuecomment-749979498

The result is now only 270 KB
