### ISSUE TITLE
Question: Cropper 100% width and/or 100% Height

### ISSUE THREAD

**Issue by silva96** [ValentinH/react-easy-crop#489]
Hi, I need your help with a good approach for this:

I need the cropper always take full width or full height of container (or both if ratio of cropper matches the container ratio)

<img width="100%" alt="image" src="https://github.com/ValentinH/react-easy-crop/assets/4019924/7418cb4b-d82a-4964-96ae-7f43d0083988">

Is this possible? I tried setting crop, initialCroppedArea, objectFit and many other things but I could not make it
Thanks in advance!

**Comment by ValentinH** [comment]
Hi,

`objectFit` should match your requirements if I'm not mistaken. Could you share a sandbox where it does not please?

**Comment by silva96** [comment]
Object fit horizontal-cover will work for the example on the right, but for the example.on the left, what object fit would work?

If we do horizontal-fit on the left example we will end up with a full width image, with a square in the middle, so could never get the same square portion that covers 100% width of the 4:5 image

I'll try to provide an example today

**Comment by ValentinH** [comment]
Just `cover` should do the job: it automatically the right setting between horizontal-cover and vertical-cover.

**Comment by silva96** [comment]
@ValentinH I tried cover but it behaves like horizontal cover in this case.

Take a look at this sandbox: https://codesandbox.io/s/heuristic-sid-8ljwzj?file=/src/index.js

I need the cropping area take that full square, but it has some paddings I can't get rid of.

I need to take a crop of the biggest square of the picture and show it as big as it can be shown inside of the container
<img width="953" alt="image" src="https://github.com/ValentinH/react-easy-crop/assets/4019924/362615c5-678d-45d8-bc08-a5d17a431efc">

**Comment by ValentinH** [comment]
This looks like a bug. The cropped area should always fill at least one direction between horizontal and vertical.

**Comment by ValentinH** [comment]
Sorry for the delay but I finally got back to this.
In the sandbox you shared, it was still using `objectFit="vertical-cover"`, using `cover` looks good to me:
![image](https://github.com/ValentinH/react-easy-crop/assets/2678610/2758c504-9c69-406e-8870-006b521b97fa)

Here's an updated sandbox: https://codesandbox.io/s/modest-golick-rttf2t?file=/src/index.js

**Comment by ValentinH** [comment]
Closing as there was no answer for a while. Comment to re-open 😉

**Comment by syedslegend786** [comment]
> Closing as there was no answer for a while. Comment to re-open 😉

https://codesandbox.io/p/sandbox/stupefied-haibt-rfgm9h?file=%2Fsrc%2Findex.js%3A24%2C13

this is the case senerio, image should be object-contained, height width could be different, 
require: cropping pan should always equal to the width and height of the image(image object contain)

**Comment by Harukisatoh** [comment]
I'm having the same issue, I tried to add the "cover" as object fit property, but then the image lose its aspect ratio.

<img width="737" alt="Image" src="https://github.com/user-attachments/assets/4f086543-9fc5-4dcb-80bf-6d6409a6074c" />

**Comment by Harukisatoh** [comment]
I just have found the solution on another issue thread. Here's the link for those that are having the same problem: https://github.com/ValentinH/react-easy-crop/issues/498#issuecomment-1790399500
