### ISSUE TITLE
Cropped image area changes when we zoom in the image , even when cropSize is given

### ISSUE THREAD

**Issue by ASHWINd199807** [ValentinH/react-easy-crop#494]
Cropped image area changes when we zoom in the image , even when cropSize is given

**To Reproduce**
1. Go to "LINK1"  select an image , select crop area, and  click on "crop".
2.  Go to "LINK2" click on "SHOW RESULT" , after that zoom to max , again click on "SHOW RESULT"

In  "LINK1" the Cropped image is always of same dimension.

But in "LINK2" THE Cropped image dimensions differ with the extent of zooming.

Could you please help me with a way so that in the "LINK2" sandbox , we can get the image of the same dimensions , that are given in cropSize , i.e. the cropped image size/dimensions does not differ with the extent of zooming

LINK1 : https://codesandbox.io/s/weathered-flower-drp62y
LINK2 : https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-forked-r6mjzj?file=/src/index.js

**Comment by ValentinH** [comment]
I think this is expected: if you make the cropper 300px wide and do a 2x zoom, the result width will be 150px.

I recommend not using the `cropSize` option and instead rely on the  `aspect`. The cropper component will automatically be responsive.
