### ISSUE TITLE
Crop area does not take up the full height/width of the image

### ISSUE THREAD

**Issue by Linyhazel** [ValentinH/react-easy-crop#498]
Thank you for this useful component! I just have a problem while using it, it's not necessary a bug, but it will be nice if you can tell me the possible problem!

**Describe the bug**
Crop area always leaves padding on the image, and is impossible to move to the edge of the image.

current:
![Screenshot 2023-11-01 at 17 48 58](https://github.com/ValentinH/react-easy-crop/assets/32091308/7aee49e0-9300-4001-8cf6-a449ff2d236b)

expected:
![Screenshot 2023-11-01 at 17 53 20](https://github.com/ValentinH/react-easy-crop/assets/32091308/c7f3deac-7db5-4de0-9483-f71a1a78edd7)

**To Reproduce**
I followed the coding example on the github, min-zoom is 1, but when the image is first loaded, the crop area doesn't take up the size of the image.

**Comment by ValentinH** [comment]
Thanks for the report. Could you share a code sandbox please?

**Comment by ValentinH** [comment]
It looks the same issue as #489.

Edit: after investigating again #489, there seems to be no issue there. Looking forward to a codesandbox showing the issue.

Did you try using `objectFit="cover"` btw?

**Comment by Linyhazel** [comment]
Hi, thanks for replying! You can find the demo here: https://codesandbox.io/s/cool-glitter-ft6x85?file=/src/App.js
I tried `objectFit="cover"`, but it's not really what i want. I want the whole image shown and the crop area takes the min(width, height) of the image.

**Comment by ValentinH** [comment]
The issue is actually coming from the modal opening animation (that is scaling the modal). If we change the animation to fading, it fixes the issue: https://codesandbox.io/s/modest-cdn-6kt49l

It's actually the same issue as #428, #409,  #267 or #400.

I will add a note about this in the README.

**Comment by ValentinH** [comment]
See https://github.com/ValentinH/react-easy-crop/pull/499

**Comment by Linyhazel** [comment]
thanks a lot!

**Comment by Harukisatoh** [comment]
Thanks @ValentinH , that was my exactly issue as well, even though I'm using shadcn dialogs instead.
