### ISSUE TITLE
Frames are lost on cropping a GIF

### ISSUE THREAD

**Issue by harsh-persona3** [ValentinH/react-easy-crop#500]
**Describe the bug**
If we try to crop a gif , the resulting output only contains a single frame of the gif i.e. it converts the uploaded gif animation to a static image after cropping when we try to view the result of the cropped gif.

**To Reproduce**
1. Go to [this demo from the docs](https://codesandbox.io/s/y09komm059)
2. Click on 'Choose File'
3. Upload a gif
4. Edit it however you like
5. Click on Show Result
6. You get a static image as the output

**Expected behavior**
The resulting image should still be a gif while maintaining all other edits such as zoom and crop

- Sandbox environment - [Demo from the docs](https://codesandbox.io/s/y09komm059)

**Comment by ValentinH** [comment]
This is because the actual cropping logic (that is not part of the library and just provided as an example) is only working for static images.
I'm not sure how we could actually crop a gif in the browser as the static way is using a canvas.
This would probably have to be done server side.

**Comment by harsh-persona3** [comment]
Thanks for the quick response. I will probably try using sharp for the above use case and since I am already using Next.js , I am guessing it should be possible using sharp

**Comment by ValentinH** [comment]
Indeed, I think that using sharp is your best option if it supports GIFs
