### ISSUE TITLE
Multiple Crop Areas

### ISSUE THREAD

**Issue by nacho-villanueva** [ValentinH/react-easy-crop#504]
**Is your feature request related to a problem? Please describe.**
I need to crop an image to an specific size. This image will then be displayed with a certain size on desktop and with another in mobile.

**Describe the solution you'd like**
I need to show multiple crop areas, so that I can show the area that will appear in mobile, while having another area for desktop, so that the user can center the image properly.

**Additional context**
![image](https://github.com/ValentinH/react-easy-crop/assets/40722107/ef6539e6-4206-4767-9346-b978833f178a)

**If you have ideas how to implement your new feature, please share!**
Allow for adding custom cropArea elements which are inside the current crop area element, therefore the width and height are already set, and can be defined relative to those.

**Comment by ValentinH** [comment]
Thanks for taking the time to open this issue and fill the template properly.

However, I think that this feature is too complex for this library and too far away for the original intent of this lib.
Indeed, the goal is to allow cropping an image in a responsive way without having to specify an explicit size. Only providing the intended aspect/ratio is enough.

Even if we were to add this feature, it would be pretty complex and require a rewrite of quite a few pieces.

For these reasons, I'm declining this feature request and encourage you to fork the lib if it's the closest one to your requirements.

Good luck!
