### ISSUE TITLE
Can this library crop images with custom aspects / resizable cropper?

### ISSUE THREAD

**Issue by najihmld** [ValentinH/react-easy-crop#505]
this is a screenshot of the **react-cropper** library
<img width="466" alt="Screen Shot 2023-12-04 at 13 13 01" src="https://github.com/ValentinH/react-easy-crop/assets/17946519/9eeb0d59-2d64-4935-95f6-c9bd7770e638">

**Comment by ValentinH** [comment]
No it can't. I indeed recommend using `react-cropper` or https://www.npmjs.com/package/react-image-crop library for this or
