### ISSUE TITLE
'Cropper' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by Rahul-Trimukhe** [ValentinH/react-easy-crop#518]
**Describe the bug**
Its instance type 'Cropper' is not a valid JSX element.
    Type 'Cropper' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, refsts(2786)

**To Reproduce**
Version "react-easy-crop": "^5.0.5",
Typescript Version 4.7

**Comment by ValentinH** [comment]
Please provide a CodeSandbox showing the issue. There is definitely something wrong in the way you import the component as we have plenty of working demos.
