### ISSUE TITLE
JSX element class does not support attributes because it does not have a 'props' property.

### ISSUE THREAD

**Issue by Rahul-Trimukhe** [ValentinH/react-easy-crop#522]
Thanks for your response on my earlier bug report.
<img width="1512" alt="Screenshot 2024-03-25 at 8 58 17 AM" src="https://github.com/ValentinH/react-easy-crop/assets/147224036/6be58aa4-ed8c-4a6f-b3a5-821b83d767e3">
Please find below repo URL I have provided you access to the repo.
https://github.com/RC-Library/EasyCrop.git

If you want we connect and screen share demo for the issue.

I would like to say Thank you for your great contribution to the community.

**Comment by ValentinH** [comment]
Thanks for the reproduction. I found a fix working on your repository. See the attached PR.

**Comment by beingtyson** [comment]
![image](https://github.com/ValentinH/react-easy-crop/assets/45677361/f7cf1ba7-5046-43ab-9e2c-e3b7049e5096)

there is still the problem

**Comment by ValentinH** [comment]
Could you please share some code?

**Comment by Rahul-Trimukhe** [comment]
Does onCropAreaChange={setCroppedArea}  has removed?
<img width="1049" alt="Screenshot 2024-04-15 at 9 03 30 PM" src="https://github.com/ValentinH/react-easy-crop/assets/147224036/b0c752b2-f6cd-47f2-9d48-196150654870">

**Comment by ValentinH** [comment]
You need to tell TS that the state is `Area |  null` in the useState call.

**Comment by Rahul-Trimukhe** [comment]
I confirm the issue has been resolved. Thanks a lot for your efforts.

**Comment by ValentinH** [comment]
You are welcome!
