### ISSUE TITLE
Allow lenient dependency on tslib

### ISSUE THREAD

**Issue by aqeelat** [ValentinH/react-easy-crop#534]
`tslib` version in package.json is `2.0.1`. Is there a specific reason why you're only allowing that version? Why not use `^2.0.1`?

It's not causing me trouble but I was auditing my yarn.lock and I noticed that I have two versions of tslib installed.

**Comment by ValentinH** [comment]
No, I don't see any reason for this. Would you like doing a PR?

**Comment by aqeelat** [comment]
Hi @ValentinH. Thank you for the prompt response. I'll open the PR soon.
I also see some other dev dependencies that are outdated. Maybe you'd want to look at them.

<img width="1287" alt="Screenshot 2024-05-02 at 12 26 47 PM" src="https://github.com/ValentinH/react-easy-crop/assets/5212744/9986b278-700e-47ce-84ad-a37878693172">

**Comment by ValentinH** [comment]
Thanks for the PR. I'll review it shortly.

Regarding outdated dev deps, I'm aware of them but it's hard to keep up with all of them. I'm really focusing on non-dev deps as they are the ones that matter for people using this lib. Dev deps are implementation details that only matter to contributors.
