### ISSUE TITLE
When using input fields for Crop X and Y values the crop completed is not triggered

### ISSUE THREAD

**Issue by alielkhateeb** [ValentinH/react-easy-crop#535]
**Describe the bug**
When I use variable inputs for crop (X and Y) that I want the user to insert in an input field, the crop does not get generated and a crop complete event is not emitted.

**To Reproduce**
1. Go to [this sandbox](https://codesandbox.io/p/sandbox/vibrant-lewin-cpxr2m?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvmo9w7q00073b6hhwjkewkn%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvmo9w7q00033b6hr4qb7d0g%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvmo9w7q00043b6hbx5bss60%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvmo9w7q00063b6hiiekm5u2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvmo9w7q00033b6hr4qb7d0g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvmo9w7q00023b6heaugdw1q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvmo9w7q00033b6hr4qb7d0g%2522%252C%2522activeTabId%2522%253A%2522clvmo9w7q00023b6heaugdw1q%2522%257D%252C%2522clvmo9w7q00063b6hiiekm5u2%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvmo9w7q00053b6ho05tp8wg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clvmo9w7q00063b6hiiekm5u2%2522%252C%2522activeTabId%2522%253A%2522clvmo9w7q00053b6ho05tp8wg%2522%257D%252C%2522clvmo9w7q00043b6hbx5bss60%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clvmo9w7q00043b6hbx5bss60%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
2. Open console
3. Move the cropped area (drag)
4. Notice in the console `Crop Complete`
5. Click on the input `Crop X`
6. Type `0`
7. You'll notice `Crop Complete` is not triggered

**Expected behavior**
I expect when input changes the crop is triggered and a cropComplete event is emitted.

**Comment by ValentinH** [comment]
This is because the `onCropComplete` is triggered at the end of a gesture (mouse up or drag stop). However, you can use the `onCropAreaChange` props that has the exact same signature than `onCropComplete` but is invoked whenever `x/y` change.
