### ISSUE TITLE
Allow setting padding for crop area

### ISSUE THREAD

**Issue by coproductions** [ValentinH/react-easy-crop#538]
**Is your feature request related to a problem? Please describe.**
When restrictPosition is set to false, it would be great if there was a way to add some padding to the sides/height of the crop area.
Currently when the image already has the correct aspect ratio or similar it fills out the entire crop area horizontally.
<img width="773" alt="Screenshot 2024-05-14 at 8 31 39 AM" src="https://github.com/ValentinH/react-easy-crop/assets/11275146/f652a13a-03a6-4ab9-8fdc-90146e6aa079">
**Describe the solution you'd like**
It would be great to allow for there always to be a certain amount of grey border around the image in the crop area, to make it clear that they can zoom in both directions.

![screenshot_2024-05-13_at_6 16 59___pm](https://github.com/ValentinH/react-easy-crop/assets/11275146/49f0e061-4c68-4b58-b8e0-d32f404586a8)

**Comment by ValentinH** [comment]
Thanks for using the issue template! 
This issue might help you: https://github.com/ValentinH/react-easy-crop/issues/502

**Comment by coproductions** [comment]
Yes that helped. thanks
