### ISSUE TITLE
Crash on ios browser when using Hotjar

### ISSUE THREAD

**Issue by erodriguezvesti** [ValentinH/react-easy-crop#541]
that's all, simply open examples on ios mobile browser and page crashes. i try with locally implementation and got the same issue

**Comment by ValentinH** [comment]
I finally managed to get access to an iOS device. I tested the website (https://valentinh.github.io/react-easy-crop/) and it works fine. What examples are you referring to?

**Comment by erodriguezvesti** [comment]
https://github.com/ValentinH/react-easy-crop/assets/118006154/4d8ab581-6321-4e89-824e-2769a6e348fb


Hi! This happens with iOS. In my implementation in my project, the same thing happens. In my project, it doesn't crash automatically, but when cropping, it collapses and throws the same error

Video if from this url -> https://codesandbox.io/s/v69ly910ql

**Comment by ValentinH** [comment]
Are you able to share the exact error from the console please?

**Comment by erodriguezvesti** [comment]
That's the problem. I tried to fix it or figure out the issue, but the console doesn't show any errors or logs. The browser just says "an error occurred" many times and crashes the page.

**Comment by ValentinH** [comment]
What about the crash on your app, not on codesandbox?

**Comment by erodriguezvesti** [comment]
Here is real time console when web site crashes

https://github.com/ValentinH/react-easy-crop/assets/118006154/d27fd3b8-5e16-41be-a217-d51a2e5aa6e5

You cannot see error messages about react easy crop

**Comment by erodriguezvesti** [comment]
https://github.com/ValentinH/react-easy-crop/assets/118006154/e6c137ec-3bd6-4c08-8de5-0635f81c430b

And this is my actual application with the problem. The browser says for 1 second that it will restart because the site failed too many times, and then the page refreshes.

**Comment by erodriguezvesti** [comment]
https://codesandbox.io/p/sandbox/react-easy-crop-v69ly910ql  fails on startup , i don't know why https://codesandbox.io/s/v69ly910ql not crashes

**Comment by ValentinH** [comment]
It seems that the app crashes when the crop button is clicked. It means that the issue isn't happening in the lib code but in the cropping function.

**Comment by erodriguezvesti** [comment]
In my implementation? No only drag  crop and crash, in code sanbox crop is loaded and crash

**Comment by erodriguezvesti** [comment]
can you test https://codesandbox.io/p/sandbox/react-easy-crop-v69ly910ql  on ios device?

**Comment by erodriguezvesti** [comment]
update: Testing previous versions, version 5.0.2 works well and the browser does not crash

**Comment by ValentinH** [comment]
Thanks for catching that. Then it means that 5.0.4 brought the issue. Are you using the objectFit property?

**Comment by erodriguezvesti** [comment]
since 5.0.3 crash on ios device.

No, i'm not using objectFit, my code is really simple

```tsx
import { useModal } from "@/context/modal/modal.provider";
import { Button } from "@nextui-org/react";
import { useCallback, useRef, useState } from "react";
import Cropper from "react-easy-crop";
import getCroppedImg from "./get-cropped-img";

interface ICropImageProps {
  b64: string;
  onConfirm: (b64: string) => void;
  onClose?: () => void;
  cropRatio?: number;
}

const CropImage = ({
  b64,
  onConfirm,
  onClose = () => {},
  cropRatio = 1 / 1,
}: ICropImageProps) => {
  const { closeModal } = useModal();
  const [crop, setCrop] = useState({ x: 0, y: 0 });
  const croppedAreaPixelsRef = useRef<any>(null);

  const onCropComplete = useCallback((croppedArea, croppedAreaPixels) => {
    croppedAreaPixelsRef.current = croppedAreaPixels;
  }, []);

  const showCroppedImage = useCallback(async () => {
    try {
      const croppedImage = await getCroppedImg(
        b64,
        croppedAreaPixelsRef.current,
        0
      );
      onConfirm(croppedImage as string);
      closeModal();
    } catch (e) {
      console.error(e);
    }
  }, [b64, onConfirm, closeModal]);

  const onCloseCrop = useCallback(() => {
    closeModal();
    onClose();
  }, [closeModal, onClose]);

  return (
    <div className="p-6">
      <div style={{ minHeight: 350, height: 350 }} className="relative">
        <Cropper
          image={b64}
          crop={crop}
          aspect={cropRatio}
          onCropChange={setCrop}
          onCropComplete={onCropComplete}
        />
      </div>

      <div className="flex justify-between mt-6">
        <Button onClick={onCloseCrop} color="danger" variant="bordered">
          Cancelar
        </Button>
        <Button onClick={showCroppedImage} color="success">
          Confirmar
        </Button>
      </div>
    </div>
  );
};

export default CropImage;
```

**Comment by ValentinH** [comment]
So it doesn't crash on 5.0.2? What I don't get is that 5.0.3 only added changes to the README 🤔

**Comment by ValentinH** [comment]
I confirm that, at the first look, nothing looks suspicious in your code. I'll try to reproduce when I'm back on my computer.

**Comment by erodriguezvesti** [comment]
Sorry, I've been testing different versions for a while and the same thing happens with all of them. Sometimes it occurs less frequently, but you can still experience the same problem. The console doesn't show any error; everything just restarts. 😔😔😔 

What seems most strange to me and could provide a clue is that in this URL https://codesandbox.io/p/sandbox/react-easy-crop-v69ly910ql the problem occurs, but in this one https://codesandbox.io/s/v69ly910ql it does not.

**Comment by ValentinH** [comment]
What version of iOS are you testing on?
I'm testing on iOS 17.5 and didn't managed to reproduce with the sandbox you shared 🤔 

![image](https://github.com/ValentinH/react-easy-crop/assets/2678610/6f9b3284-c6af-4f1b-b8ec-e6e4b04b2ec4)

Do you manage to reproduce on the preview url: https://v69ly910ql.csb.app?

**Comment by ValentinH** [comment]
> What seems most strange to me and could provide a clue is that in this URL [codesandbox.io/p/sandbox/react-easy-crop-v69ly910ql](https://codesandbox.io/p/sandbox/react-easy-crop-v69ly910ql) the problem occurs, but in this one [codesandbox.io/s/v69ly910ql](https://codesandbox.io/s/v69ly910ql) it does not.

These are 2 different versions of the codesandbox editor. Therefore, I would say that the issue is more on the codesandbox side than on the lib itself.

Are you able to create a small repository of your example that still reproduces the error and share it here please? The goal is to remove codesandbox from the equation.

**Comment by erodriguezvesti** [comment]
After a thousand tests, the error occurs when having a tracking provider like Clarity or Hotjar; when initializing the crop or moving the image, the site crashes. I imagine it must be issues with these services. For now, I solved it by disabling Clarity on my website. Many thanks for your help and follow-up.

**Comment by erodriguezvesti** [comment]
> What version of iOS are you testing on? I'm testing on iOS 17.5 and didn't managed to reproduce with the sandbox you shared 🤔
> 
> ![image](https://private-user-images.githubusercontent.com/2678610/341966234-6f9b3284-c6af-4f1b-b8ec-e6e4b04b2ec4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzg2NjEsIm5iZiI6MTcxOTA3ODM2MSwicGF0aCI6Ii8yNjc4NjEwLzM0MTk2NjIzNC02ZjliMzI4NC1jNmFmLTRmMWItYjhlYy1lNmU0YjA0YjJlYzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjJUMTc0NjAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODFhYzA5Y2QzMDkyN2U0NTY4NTc1MWE1Y2FlYjc2MWYxZDdlYTk4MzgxNzZhNTM4MGVkYWY1ODE3ZTE3ODhkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hcSVxkRojs6BmTrKVUXYYHYHhivtIUiX5fdQWTh8_84)
> 
> Do you manage to reproduce on the preview url: https://v69ly910ql.csb.app?

That's a point, the error only occurs on real devices. I couldn't reproduce it on the emulator either, but I did on four real devices.

**Comment by ValentinH** [comment]
> After a thousand tests, the error occurs when having a tracking provider like Clarity or Hotjar; when initializing the crop or moving the image, the site crashes. I imagine it must be issues with these services. For now, I solved it by disabling Clarity on my website. Many thanks for your help and follow-up. 

That's very interesting! I've never heard about such issues, it would be great to see at what line it throws so that we can find a solution.
