### ISSUE TITLE
Croparea is not restored after zoom

### ISSUE THREAD

**Issue by gerbensnellenberg** [ValentinH/react-easy-crop#547]
**Describe the bug**
I use the cropper with a container that has the same size as the cropper, both width as heigth.
When rotating an image, the croparea will resize to the dimensions of the rotated image (smaller). The croparea does not return to it's initial size, for example when zooming in.

**To Reproduce**
1. Rotate (2nd scroller) the image 90deg, the croparea will become smaller
2. Zoom in (1st scroller) 

**Expected behavior**
I would like to see that the croparea would expand to the size of the container if you zoom in on the rotated image. This could also be achieved when you have the possibilty to change the size of the cropArea.

https://codesandbox.io/p/sandbox/sharp-archimedes-32pzkk

**Comment by ValentinH** [comment]
Hi,

The sandbox link is broken apparently.
