### ISSUE TITLE
Vertical reposition shows blank screen "react-easy-crop": "5.0.7",

### ISSUE THREAD

**Issue by PDipendra** [ValentinH/react-easy-crop#548]
Initially its good 
![Screenshot 2024-07-18 at 19 27 14](https://github.com/user-attachments/assets/252e8b4d-a03b-4e10-85fc-9f1b6586428b)

But when i move vertically it shows 
![Screenshot 2024-07-18 at 19 28 39](https://github.com/user-attachments/assets/1e104eab-c062-445f-a562-06e84ac8efd9)

const [crop, setCrop] = useState({ x: 0, y: 0 })
  const [zoom, setZoom] = useState(1);

  return (
      <div className={styles.container}>
          <div className={styles.cropperWrapper}>
              <Cropper
                  image={'https://images.pexels.com/photos/19176962/pexels-photo-19176962/free-photo-of-passenger-train-in-blurred-motion.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'}
                  crop={crop}
                  zoom={zoom}
                  aspect={3 / 1}
                  onCropChange={setCrop}
                  onZoomChange={setZoom}
                  classes={{
                    cropAreaClassName: styles.cropperArea
                  }}
                  objectFit="horizontal-cover"
                  restrictPosition={true}
              />
          </div>
      </div>
  );

.container {
    position: relative;
    background-color: lavender;
    max-height: 90vh;
    min-height: 90vh;
    width: 900px;
    margin: 5rem auto 0;

    .cropperWrapper {
        background-color: rgb(13, 173, 96);
        height: 300px;
        width: 100%;
        position: absolute;
        top: 0;
        left: 0;
        right: 0;

        .cropperArea {
            width: 100% !important;
            height: 100% !important;
        }
    }
}

**Comment by ValentinH** [comment]
Why do you override the internal CSS classes?
