### ISSUE TITLE
InitialCroppedAreaPixels no longer works properly after v5 upgrade

### ISSUE THREAD

**Issue by itsUndefined** [ValentinH/react-easy-crop#550]
**Describe the bug**
After upgrading to react-easy-crop 5 I noticed a few things:
1) The image is first loaded and rendered on the screen without any max-width/max-height. This flashes the image for 1 frame on the browser. 
2) The `onMediaLoaded` callback also reflects 1) as the returned media size has the same natural and current width/height.
3) The `initialCroppedAreaPixels` no longer works properly because it uses the wrong media size for calculation
4) The `setMediaSize` callback is called twice on component mount. The second time it's called with the correct media size but it's too late for the correct `initialCroppedAreaPixels` to work.

I suspect that this PR broke the initialCroppedAreaPixels feature: [#506](https://github.com/ValentinH/react-easy-crop/pull/506) because it doesn't set a default mediaObjectFit inside the Cropper.tsx fast enough. It does it after the initial render. The initial render is completed with this value being undefined.

**Expected behavior**
I expected the prop `initialCroppedAreaPixels` to render the cropper with the state of the saved crop.

**Comment by ValentinH** [comment]
Thank you for finding this issue and sorry for the bug.
