### ISSUE TITLE
objectFit="cover" prevents to zoom out

### ISSUE THREAD

**Issue by mightym** [ValentinH/react-easy-crop#566]
**Describe the bug**
When I use `objectFit="cover"` together with `aspect={1} cropShape="round"` I can't zoom the image to fit the crop area. The crop area is always smaller than the possible max crop area available: 

In that screenshot my image is a square image. And you can see that there is still a lot of space left to zoom in. But you can't:

<img width="732" alt="1" src="https://github.com/user-attachments/assets/41d1d07d-c64e-49d1-933a-1b09cadf88c0">

**To Reproduce**
1. Open the example below
2. Upload a small square image

**Expected behavior**
I expect to zoom in on the image so that it fully covers the crop area. 

- Please create a CodeSandbox that demonstrates your issue. 
https://codesandbox.io/p/sandbox/react-easy-crop-custom-image-demo-forked-lgqh52?file=%2Fsrc%2Findex.js%3A81%2C15&workspaceId=bc8b6897-580d-458a-9b3c-d003c96a2633

**Comment by ValentinH** [comment]
Do you expect to zoom in or out? The thing is that zooming out would lead to empty spaces at the top and bottom of the image..the library prevents that by default.
However, you can set `restrictPosition` to `false` to disable this.

**Comment by mightym** [comment]
I leave you my sample image here. Also try to make  your browser window smaller and larger. 
Both zoom direction have in the example screenshot above enough space. 

![10](https://github.com/user-attachments/assets/95e23e6a-bcb3-4c2e-ad89-c1843ce967c8)

Will try to prepare a screen capture video for you.

**Comment by mightym** [comment]
This is after I selected the image: 


https://github.com/user-attachments/assets/be4c4aea-cdfd-4cbf-a765-93a2ff50c9af

**Comment by ValentinH** [comment]
The thing is that `zoom: 1` means that the image covers its container. If your cropped area is squared then it's better to have the container to be a square as well.

See this quick example: https://codesandbox.io/p/sandbox/react-easy-crop-custom-image-demo-forked-cghhr6

<img width="732" alt="image" src="https://github.com/user-attachments/assets/1957b9f5-b1a8-4e98-a0e0-64dd5902a6f8">

**Comment by arastu-diwan** [comment]
Hi ValentinH,

I tried your solution to enable zooming out while cropping the full image, but if we try to crop the full image, there is some transparent space that also comes after the cropped image.
I only want the image and don't need this extra transparent space.
How to resolve this issue now??
![Screenshot 2024-11-27 200854](https://github.com/user-attachments/assets/2b874e3e-3a88-434c-b6de-fc8dfabb5b96)

**Comment by ValentinH** [comment]
This transparent area means that your actual cropping logic (the one that takes the original image and produces the new one) should be adapted to remove this empty space. This is outside of the library.
