### ISSUE TITLE
Improvements to keyboard support

### ISSUE THREAD

**Issue by IanSymplectic** [ValentinH/react-easy-crop#574]
**Is your feature request related to a problem? Please describe.**
We're very happy that keyboard support has been added to react-easy-crop, as it removed the need for our custom wrapper around it, but we hope we can introduce a couple of tweaks to improve things.

**Describe the solution you'd like**
Currently (v5.1.0), using the arrow keys while the cropper is focused causes scrolling because preventDefault() isn't being called on the event. It would be better if `preventDefault()` were called, to prevent scrolling while moving the crop area.
Also, as there is a single fixed step size it can be hard to finely tune the desired area. It seems technically possible to work around this by zooming in further than desired, moving by the fixed step size and then zooming back out and correcting, but this is cumbersome and unintuitive. It would be nice if a modifier key could scale the step size down (say, by a factor of 5) to move the crop area in smaller increments. Our previous wrapper used the shift key for this finer control.

**Describe alternatives you've considered**
Our previous alternative was to wrap the cropper with our own custom keyboard interaction handing, but as react-easy-crop supports keyboard interaction natively we'd like to avoid the need for that. As of 5.1.0 we still have a slim wrapper just to cancel the scrolling caused by the arrow keys, and have accepted the slight regression in our interface caused by the lack of finer control, but it'd be nice to not need either.

**Additional context**
We'd be happy to make a pull request for these changes if you're happy with the ideas.

- If you have ideas how to implement your new feature, please share!
We could build on JGuardiola95's commit https://github.com/ValentinH/react-easy-crop/pull/570/commits/5f6a353ead6afa3ad04c0782779b64ffc0d1d110 to add `preventDefault()` in the `case`  blocks in `onKeyDown`, and multiply `step` by 0.2 before the `switch` if shift is pressed.

**Comment by ValentinH** [comment]
I like this idea. You are very welcome to create a PR, I'll be happy to review it 🙂

**Comment by ValentinH** [comment]
The improvement was released in https://github.com/ValentinH/react-easy-crop/releases/tag/v5.2.0.
