### ISSUE TITLE
Crop Area does not fit the entire width of the image

### ISSUE THREAD

**Issue by wshihdehx** [ValentinH/react-easy-crop#578]
**Describe the bug**
The crop area does not adjust to the width of the image 

![image](https://github.com/user-attachments/assets/8ba475ad-7cf9-4156-ac6a-41b062bd1418)

However when I resize the browser window the crop area dimensions get fixed

![image](https://github.com/user-attachments/assets/4cabac42-c8f1-414e-82a9-5caef5b0e672)

`

       const aspectDefault = 16 / 9;
   
       const cropShapeProp = 'rectangle';

    const TableContainer = styled.div'
      width: 100%;
      display: table;
      background: ${getColorToken('Container/Neutral/Mute 2')};
      height: 478px;
    `;
    const TableCellContainer = styled.div'
      height: 100%;
      vertical-align: middle;
      display: table-cell;
      text-align: center;
    ';

    const CropContainer = styled.div`
      height: 361px;
      position: relative;
      margin-bottom: 32px;

      .reactEasyCrop_CropArea {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        border: 2px solid rgb(154, 107, 94);
        box-sizing: border-box;
        box-shadow: 0 0 0 9999em;
        color: rgba(9, 9, 9, 0.6);
        overflow: hidden;
      }
    ';

          <TableContainer>
            <TableCellContainer>
              <CropContainer>
                <Cropper
                  image={srcUrl}
                  crop={crop}
                  zoom={zoom}
                  aspect={aspectDefault}
                  cropShape={cropShapeProp}
                  showGrid={false}
                  zoomWithScroll={true}
                  maxZoom={3}
                  onCropChange={(cropCords: Point) => setCrop(cropCords)}
                  onCropComplete={onCropComplete}
                  onZoomChange={(zoomChange: number) => setZoom(zoomChange)}
                />
              </CropContainer>
              <Box textStyle="Body/Small/Regular">Drag to move</Box>
            </TableCellContainer>
`

**Comment by ValentinH** [comment]
It seems that you are rendering the cropper inside a modal. You should wait for the modal to be fully open (transition completed to render the cropper). You can check existing issues related to "modals".

**Comment by ValentinH** [comment]
You can also check the "Known issues" in the readme.

**Comment by wshihdehx** [comment]
Thanks @ValentinH setting motionPreset="none" on the chakra modal component fixes the issue! Much appreciated!
